org: clouding

service: basls

frameworkVersion: "4"

package: 
  individually: true
  patterns: ['package.json'] 

build:
  esbuild:
    format: esm
    minify: true
    bundle: true
    external:  
      - @aws-sdk/client-s3
    exclude:  
      - @aws-sdk/*
    packages: external
    buildConcurrency: 3
    sourcemap:
      type: linked
      setNodeOptions: true
    
plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  memorySize: 128

functions:
  welcome:
    handler: src/functions/welcome.handler
    events:
      - httpApi:
          path: /welcome/{identifier}
          method: GET
  pong:
    handler: src/functions/pong.handler
    events:
      - httpApi:
          path: /pong
          method: GET
