# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: clouding
# "service" is the name of this project. This will also be added to your AWS resource names.
service: basls

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  memorySize: 128

functions:
  ping:
    handler: src/functions/ping.handler
    events:
      - httpApi:
          path: /ping
          method: GET
  pong:
    handler: src/functions/pong.handler
    events:
      - httpApi:
          path: /pong/{message}
          method: GET
